[package]
name = "shared_no_tto"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/devnet" }
common = { local = "../common" }

[addresses]
shared_no_tto = "0x0"
